name: Health check
on:
  push:
    branches:
      - main
jobs:
  Perodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Simulate Failure Step
        run: exit 1
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Check the following url
          url: https://pokemon-app-4lxo.onrender.com/health
          max-attempts: 3
          retry-delay: 45s