name: Deployment pipeline

on:
  push:
    branches:
      - test
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: e2e tests
        uses: cypress-io/github-action@v3
        with:
            build: npm run build
            start: npm run start-prod      
            command: npm run test:e2e           
            browser: chrome
            wait-on: 'http://localhost:5000'
            headless: true